### ISSUE TITLE
Crashing Report via adb

### ISSUE THREAD

**Issue by ghost** [SongTube/SongTube-New#1]
<pre>
I/System.out: flutterEngine warmed up
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.artxdev.songtube.dev, PID: 6352
    java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
        at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
        at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invokeSuspend(WindowInfoTrackerImpl.kt:52)
        at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:8)
        at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
        at androidx.window.java.layout.WindowInfoTrackerCallbackAdapter$addListener$1$1.invokeSuspend(WindowInfoTrackerCallbackAdapter.kt:96)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
W/System: A resource failed to call close. 
</pre>

Can you fix it?
This is the tested environment:

<pre>
AvdId=Pixel_C_API_33
PlayStore.enabled=false
abi.type=x86_64
avd.ini.displayname=Pixel C API 33
avd.ini.encoding=UTF-8
disk.dataPartition.size=10G
fastboot.chosenSnapshotFile=
fastboot.forceChosenSnapshotBoot=no
fastboot.forceColdBoot=no
fastboot.forceFastBoot=yes
hw.accelerometer=yes
hw.arc=false
hw.audioInput=yes
hw.battery=yes
hw.camera.back=virtualscene
hw.camera.front=emulated
hw.cpu.arch=x86_64
</pre>

**Comment by ghost** [comment]
I Fixed that by add implementations.
<pre>
dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
    implementation "androidx.window:window:1.0.0-rc01"
    implementation "androidx.window:window-java:1.0.0-rc01"
}
</pre>

but It crashed again..
<pre>
D/TrafficStats: tagSocket(180) with statsTag=0xffffffff, statsUid=-1
I/ExoPlayerImpl: Init d333f33 [ExoPlayerLib/2.17.1] [emu64xa, sdk_gphone64_x86_64, Google, 33]
W/ev.songtube.dev: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
D/COOKIE: 
E/SurfaceSyncer: Failed to find sync for id=0
W/Parcel: Expecting binder but got null!
E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.artxdev.songtube.dev, PID: 8925
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/Math8;
        at j$.time.Duration.ofSeconds(Duration.java:245)
        at j$.time.temporal.ChronoUnit.<clinit>(ChronoUnit.java:190)
        at j$.time.temporal.ChronoField.<clinit>(ChronoField.java:120)
        at j$.time.LocalDate.of(LocalDate.java:266)
        at j$.time.LocalDate.<clinit>(LocalDate.java:144)
        at j$.time.LocalDateTime.<clinit>(LocalDateTime.java:144)
        at j$.time.OffsetDateTime.<clinit>(OffsetDateTime.java:138)
        at org.schabi.newpipe.extractor.localization.TimeAgoParser.<init>(TimeAgoParser.java:32)
        at org.schabi.newpipe.extractor.localization.TimeAgoPatternsManager.getTimeAgoParserFor(TimeAgoPatternsManager.java:27)
        at org.schabi.newpipe.extractor.StreamingService.getTimeAgoParser(StreamingService.java:383)
        at org.schabi.newpipe.extractor.Extractor.getTimeAgoParser(Extractor.java:152)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getInitialPage(YoutubeTrendingExtractor.java:97)
        at com.artxdev.newpipeextractor_dart.youtube.YoutubeTrendingExtractorImpl.getTrendingPage(YoutubeTrendingExtractorImpl.java:22)
        at com.artxdev.newpipeextractor_dart.NewpipeextractorDartPlugin$1.run(NewpipeextractorDartPlugin.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.Math8" on path: DexPathList[[zip file "/data/app/~~69A1N5FdzYqhyKUrlHnFRg==/com.artxdev.songtube.dev-fRGiR63-iXezhAIo3_T6_Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~69A1N5FdzYqhyKUrlHnFRg==/com.artxdev.songtube.dev-fRGiR63-iXezhAIo3_T6_Q==/lib/x86_64, /data/app/~~69A1N5FdzYqhyKUrlHnFRg==/com.artxdev.songtube.dev-fRGiR63-iXezhAIo3_T6_Q==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at j$.time.Duration.ofSeconds(Duration.java:245) 
        at j$.time.temporal.ChronoUnit.<clinit>(ChronoUnit.java:190) 
        at j$.time.temporal.ChronoField.<clinit>(ChronoField.java:120) 
        at j$.time.LocalDate.of(LocalDate.java:266) 
        at j$.time.LocalDate.<clinit>(LocalDate.java:144) 
        at j$.time.LocalDateTime.<clinit>(LocalDateTime.java:144) 
        at j$.time.OffsetDateTime.<clinit>(OffsetDateTime.java:138) 
        at org.schabi.newpipe.extractor.localization.TimeAgoParser.<init>(TimeAgoParser.java:32) 
        at org.schabi.newpipe.extractor.localization.TimeAgoPatternsManager.getTimeAgoParserFor(TimeAgoPatternsManager.java:27) 
        at org.schabi.newpipe.extractor.StreamingService.getTimeAgoParser(StreamingService.java:383) 
        at org.schabi.newpipe.extractor.Extractor.getTimeAgoParser(Extractor.java:152) 
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getInitialPage(YoutubeTrendingExtractor.java:97) 
        at com.artxdev.newpipeextractor_dart.youtube.YoutubeTrendingExtractorImpl.getTrendingPage(YoutubeTrendingExtractorImpl.java:22) 
        at com.artxdev.newpipeextractor_dart.NewpipeextractorDartPlugin$1.run(NewpipeextractorDartPlugin.java:308) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
        at java.lang.Thread.run(Thread.java:1012) 
I/Process: Sending signal. PID: 8925 SIG: 9
Disconnected from the target VM, address: 'localhost:8432', transport: 'socket'
</pre>

I'll try to fix it. sorry for the inconvenience.

**Comment by ghost** [comment]
update the desugar_jdk_libs to 1.1.5

<pre>
dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
    implementation "androidx.window:window:1.0.0-rc01"
    implementation "androidx.window:window-java:1.0.0-rc01"
}
</pre>

![캡처](https://user-images.githubusercontent.com/115380484/194743245-5c842369-7f38-48d5-a360-a18189ed3576.PNG)

Finally!
